zeus_site:
    resource: "@ZeusSiteBundle/Resources/config/routing.yml"
    prefix:   /
    
zeus_user:
    resource: "@ZeusUserBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
_imagine:
    resource: .
    type:     imagine

