# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_OLYMPIENS:     ROLE_USER
        ROLE_ADMIN:         [ROLE_OLYMPIENS, ROLE_USER]
        #ROLE_SUPER_ADMIN:   [ROLE_USER, ROLE_ADMIN, ROLE_OLYMPIENS]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                remember_me: true
            remember_me:
                key: %secret%
            logout: true
            anonymous: true

    access_control:
        
        # Controle d'acces pour les utilisateurs anonyme
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
         # Controle d'acces pour les utilisateurs normaux
        - { path: ^/$, roles: ROLE_USER}
        - { path: ^/profiles, roles: ROLE_USER}
        - { path: ^/emprunts, roles: ROLE_USER}
        - { path: ^/contact, roles: ROLE_USER}
        
        # Controle d'acces pour les administrateurs
        - { path: ^/register, roles: ROLE_ADMIN}
        - { path: ^/utilisateurs, roles: ROLE_ADMIN}

        # Controle d'acces pour les olympiens
        - { path: ^/auteurs, roles: ROLE_OLYMPIENS }
        - { path: ^/types_parutions, roles: ROLE_OLYMPIENS }
        - { path: ^/parutions, roles: ROLE_OLYMPIENS }
        - { path: ^/traducteurs, roles: ROLE_OLYMPIENS }
        - { path: ^/editeurs, roles: ROLE_OLYMPIENS }
        
        
       
        

        
       

        
        
        
