<?php

namespace Zeus\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieParutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieParutionRepository extends EntityRepository
{
}
