<?php

namespace Zeus\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditionRepository extends EntityRepository
{
    public function findAllByParution($parution)
    {
        return $this->createQueryBuilder('e')
                  ->where('e.parution = :idParution')
                  ->setParameter('idParution', $parution->getId())
                 ->orderBy('e.numero', 'ASC')
                  ->getQuery()
                  ->getResult();
    }
}
