<?php

namespace Zeus\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * ParutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParutionRepository extends EntityRepository
{
	
	public function aaLasts()
        {	
           $queryBuilder = $this->_em->createQueryBuilder()
                                     ->select('p.id')
                                     ->from($this->_entityName, 'p');
           $query = $queryBuilder->getQuery();
           $resultats = $query->getResult();

           return $resultats;
	}
}
