<?php

namespace Zeus\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SousCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousCategorieRepository extends EntityRepository
{
    public function findAllByCategorie($categorie){
        
      return $this->createQueryBuilder('sc')
                  ->where('sc.categorie = :idCategorie')
                  ->setParameter('idCategorie', $categorie->getId())
                 ->orderBy('sc.codeClassification', 'ASC')
                  ->getQuery()
                  ->getResult();
      
    }
}
