zeus_user_utilisateur_tableau:
    pattern: /utilisateurs
    defaults: { _controller: ZeusUserBundle:Utilisateur:index }

zeus_user_utilisateur_ajout:
    pattern: /utilisateurs/ajouter
    defaults: { _controller: ZeusUserBundle:Utilisateur:ajouter }

zeus_user_utilisateur_modif:
    pattern: /utilisateurs/modifier/{idUtilisateur}
    defaults: { _controller: ZeusUserBundle:Utilisateur:modifier }

zeus_user_utilisateur_suppr:
    pattern: /utilisateurs/supprimer
    defaults: { _controller: ZeusUserBundle:Utilisateur:supprimer }

fos_user_security:
    resource: "routing/security.xml"

fos_user_profile:
    resource: "routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "routing/change_password.xml"
    prefix: /profile

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /groupe