_imagine:
    resource: .
    type:     imagine

zeus_site_homepage:
    pattern:  /
    defaults: { _controller: ZeusSiteBundle:Accueil:index }

zeus_site_auteur_tableau:
    pattern: /auteurs
    defaults: { _controller: ZeusSiteBundle:Auteur:index }
    
zeus_site_auteur_ajout:
    pattern: /auteurs/ajouter
    defaults: { _controller: ZeusSiteBundle:Auteur:ajouter }

zeus_site_auteur_modif:
    pattern: /auteurs/modifier/{idAuteur}
    defaults: { _controller: ZeusSiteBundle:Auteur:modifier }

zeus_site_parution_tableau:
    pattern: /parutions
    defaults: { _controller: ZeusSiteBundle:Parution:index }

zeus_site_parution_ajout:
    pattern: /parutions/ajouter
    defaults: { _controller: ZeusSiteBundle:Parution:ajouter }
    
zeus_site_parution_modif:
    pattern: /parutions/modifier/{idParution}
    defaults: { _controller: ZeusSiteBundle:Parution:modifier }

zeus_site_typeparution_tableau:
    pattern: /types-parutions
    defaults: { _controller: ZeusSiteBundle:TypeParution:index }
    
zeus_site_typeparution_ajout:
    pattern: /types-parutions/ajouter
    defaults: { _controller: ZeusSiteBundle:TypeParution:ajouter }
    
zeus_site_typeparution_modif:
    pattern: /types-parutions/modifier/{idTypeParution}
    defaults: { _controller: ZeusSiteBundle:TypeParution:modifier }
    
zeus_site_informationuser_edit:
    pattern: /informationuser/edit
    defaults: { _controller: ZeusSiteBundle:User:edit }