_imagine:
    resource: .
    type:     imagine

zeus_site_homepage:
    pattern:  /
    defaults: { _controller: ZeusSiteBundle:Accueil:index }

zeus_site_auteur_tableau:
    pattern: /auteurs
    defaults: { _controller: ZeusSiteBundle:Auteur:index }
    
zeus_site_auteur_ajout:
    pattern: /auteurs/ajouter
    defaults: { _controller: ZeusSiteBundle:Auteur:ajouter }

zeus_site_auteur_modif:
    pattern: /auteurs/modifier/{idAuteur}
    defaults: { _controller: ZeusSiteBundle:Auteur:modifier }
    
zeus_site_auteur_suppr:
    pattern: /auteurs/supprimer/{idAuteur}
    defaults: { _controller: ZeusSiteBundle:Auteur:supprimer }
    
zeus_site_traducteur_tableau:
    pattern: /traducteurs
    defaults: { _controller: ZeusSiteBundle:Traducteur:index }
    
zeus_site_traducteur_ajout:
    pattern: /traducteurs/ajouter
    defaults: { _controller: ZeusSiteBundle:Traducteur:ajouter }

zeus_site_traducteur_modif:
    pattern: /traducteurs/modifier/{idTraducteur}
    defaults: { _controller: ZeusSiteBundle:Traducteur:modifier }
    
zeus_site_traducteur_suppr:
    pattern: /traducteurs/supprimer/{idTraducteur}
    defaults: { _controller: ZeusSiteBundle:Traducteur:supprimer }
    
zeus_site_parution_tableau:
    pattern: /parutions
    defaults: { _controller: ZeusSiteBundle:Parution:index }

zeus_site_parution_ajout:
    pattern: /parutions/ajouter
    defaults: { _controller: ZeusSiteBundle:Parution:ajouter }
    
zeus_site_parution_modif:
    pattern: /parutions/modifier/{idParution}
    defaults: { _controller: ZeusSiteBundle:Parution:modifier }
    
zeus_site_parution_suppr:
    pattern: /parutions/supprimer/{idParution}
    defaults: { _controller: ZeusSiteBundle:Parution:supprimer }

zeus_site_typeparution_tableau:
    pattern: /types-parutions
    defaults: { _controller: ZeusSiteBundle:TypeParution:index }
    
zeus_site_typeparution_ajout:
    pattern: /types-parutions/ajouter
    defaults: { _controller: ZeusSiteBundle:TypeParution:ajouter }
    
zeus_site_typeparution_modif:
    pattern: /types-parutions/modifier/{idTypeParution}
    defaults: { _controller: ZeusSiteBundle:TypeParution:modifier }
    
zeus_site_typeparution_suppr:
    pattern: /types-parutions/supprimer/{idTypeParution}
    defaults: { _controller: ZeusSiteBundle:TypeParution:supprimer }
    
zeus_site_informationuser_edit:
    pattern: /informationuser/edit
    defaults: { _controller: ZeusSiteBundle:User:edit }
    
zeus_site_editeurs_tableau:
    pattern: /editeurs
    defaults: { _controller: ZeusSiteBundle:Editeur:index }
    
zeus_site_editeurs_ajout:
    pattern: /editeurs/ajouter
    defaults: { _controller: ZeusSiteBundle:Editeur:ajouter }

zeus_site_editeurs_modif:
    pattern: /editeurs/modifier/{idEditeur}
    defaults: { _controller: ZeusSiteBundle:Editeur:modifier }