parameters:
#    zeus_site.example.class: Zeus\SiteBundle\Example

services:
#    zeus_site.example:
#        class: %zeus_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
