Categorie:
    type: entity
    table: categorie
    fields:
        idCategorie:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_categorie
            generator:
                strategy: IDENTITY
        codeClassification:
            type: integer
            unsigned: false
            nullable: false
            column: code_classification
        intitule:
            type: string
            length: 500
            fixed: false
            nullable: false
    manyToMany:
        idParution:
            targetEntity: Parution
            cascade: {  }
            mappedBy: idCategorie
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
