Droit:
    type: entity
    table: droit
    fields:
        idDroit:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_droit
        nomDroit:
            type: string
            length: 20
            fixed: false
            nullable: false
            column: nom_droit
    oneToOne:
        idGroupe:
            targetEntity: Groupe
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_groupe:
                    referencedColumnName: id_groupe
            orphanRemoval: false
    lifecycleCallbacks: {  }
