Emprunt:
    type: entity
    table: emprunt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        datedebut:
            type: datetime
            nullable: false
        datefin:
            type: datetime
            nullable: true
    manyToOne:
        parution:
            targetEntity: Parution
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                parution_id:
                    referencedColumnName: id
            orphanRemoval: false
        employe:
            targetEntity: Utilisateur
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                employe_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
