Groupe:
    type: entity
    table: groupe
    fields:
        idGroupe:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_groupe
        idService:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_service
        nomGroupe:
            type: string
            length: 20
            fixed: false
            nullable: false
            column: nom_groupe
    lifecycleCallbacks: {  }
