Traducteur:
    type: entity
    table: traducteur
    fields:
        idTraducteur:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_traducteur
            generator:
                strategy: IDENTITY
        prenomTraducteur:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: prenom_traducteur
        nomTraducteur:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: nom_traducteur
    manyToMany:
        idParution:
            targetEntity: Parution
            cascade: {  }
            mappedBy: idTraducteur
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
