TypeParution:
    type: entity
    table: type_parution
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        libelle:
            type: string
            length: 50
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
